spring.application.name=auth-service
server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

jwt.secret=FAhTKmBPlck8pyH65vkzBPLnAG2GIHT9edNjCHlslLJ
jwt.expiration=3600000

grpc.server.port=-1

grpc.client.user-service.address=static://localhost:9090
grpc.client.user-service.negotiation-type=plaintext

resilience4j.circuitbreaker.configs.default.sliding-window-size=10
resilience4j.circuitbreaker.configs.default.minimum-number-of-calls=5
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=50
resilience4j.circuitbreaker.configs.default.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.configs.default.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.user-service.base-config=default
resilience4j.circuitbreaker.instances.user-service.ignore-exceptions=com.ezedin.Auth_Service.exception.DuplicateUsernameException,com.ezedin.Auth_Service.exception.DuplicateEmailException,com.ezedin.Auth_Service.exception.UserNotFoundException

management.endpoints.web.exposure.include=health,circuitbreakers,circuitbreakerevents
management.health.circuitbreakers.enabled=true
