spring.application.name=auth-service
server.port=8083

jwt.secret=FAhTKmBPlck8pyH65vkzBPLnAG2GIHT9edNjCHlslLJ
jwt.expiration=3600000

# Auth is gRPC client only; disable embedded server (default port 9090 conflicts with user-service)
grpc.server.port=-1

grpc.client.user-service.address=static://localhost:9090
grpc.client.user-service.negotiation-type=plaintext
